services:
    # default configuration for services in *this* file
    _defaults:
        autowire: false      # Automatically injects dependencies in your services.
        public: false
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Xact\CommandScheduler\Command\:
        autowire: true
        public: true
        resource: '../../Command/*'
        tags: [command_handler]

    Xact\CommandScheduler\Controller\:
        public: true
        autowire: true
        resource: '../../Controller/*'

    Xact\CommandScheduler\Form\:
        public: true
        autowire: true
        resource: '../../Form/*'

    Xact\CommandScheduler\Scheduler\:
        public: true
        autowire: true
        resource: '../../Scheduler/*'
        exclude: '../../Scheduler/ActiveCommand.php'

    Xact\CommandScheduler\Service\:
        public: true
        autowire: true
        resource: '../../Service/*'
