services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Xact\CommandScheduler\:
        public: true
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Resources,Scheduler,Tests}'

    Xact\CommandScheduler\Command\:
        public: true
        resource: '../../Command/*'
        tags: [command_handler]

    Xact\CommandScheduler\Scheduler\CommandScheduler:
        public: true
        autowire: true
