services:
    # default configuration for services in *this* file
    _defaults:
        autowire: false      # Automatically injects dependencies in your services.
        public: false
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Xact\CommandScheduler\CommandSchedulerFactory:
        public: true
        autowire: true
        arguments:
            $clearData: '%xact_command_scheduler.clear_data%'
            $retryOnFail: '%xact_command_scheduler.retry_on_fail%'
            $retryDelay: '%xact_command_scheduler.retry_delay%'
            $retryMaxAttempts: '%xact_command_scheduler.retry_max_attempts%'

    Xact\CommandScheduler\Command\:
        autowire: true
        public: true
        resource: '../src/Command/*'
        tags: [command_handler]

    Xact\CommandScheduler\Controller\:
        public: true
        autowire: true
        resource: '../src/Controller/*'

    Xact\CommandScheduler\Form\:
        public: true
        autowire: true
        resource: '../src/Form/*'

    Xact\CommandScheduler\Repository\:
        public: true
        autowire: true
        resource: '../src/Repository/*'

    Xact\CommandScheduler\Scheduler\:
        public: true
        autowire: true
        resource: '../src/Scheduler/*'
        exclude: '../src/Scheduler/ActiveCommand.php'

    Xact\CommandScheduler\Service\:
        public: true
        autowire: true
        resource: '../src/Service/*'
